logging:
  level:
    root: info
    sql: ERROR

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  access:
    expiration: 60000
    header: Authorization

  refresh:
    expiration: 1209600000 # 2?
    header: Authorization-refresh
